//! Keyboard intents. Crossterm events become these; `app.rs` executes them.

#[derive(Clone, Debug, PartialEq)]
pub enum Intent {
    Up,
    Down,
    Left,
    Right,
    PageDown,
    PageUp,
    First,
    Last,
    DetailScrollDown,
    DetailScrollUp,
    FilterCycle,
    ToggleSelect,
    Enter,
    Search,
    Refresh,
    Update,
    DeleteMenu,
    CancelDownload,
    VerifyGame,
    ImportGame,
    CloudSaves,
    Settings,
    Help,
    OpenStore,
    Quit,
    Cancel,
    ConfirmYes,
    ConfirmNo,
    Char(char),
    Backspace,
}
